name: CI

on:
    push:
        branches: [ 6.0 ]
    pull_request:
        branches: [ 6.0 ]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: [ '8.4' ]
                composer-prefer: [ '', '--prefer-lowest --prefer-stable' ]

        steps:
            -   uses: actions/checkout@v6

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: xdebug
                    tools: composer:v2

            -   name: Validate composer.json
                run: composer validate --strict --no-check-lock

            -   name: Cache Composer packages
                uses: actions/cache@v5
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.composer-prefer }}-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-${{ matrix.php-version }}-

            -   name: Install dependencies
                run: composer update --prefer-dist --no-interaction --no-progress ${{ matrix.composer-prefer }}

            -   name: Run tests
                run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=clover.xml

            -   name: Run PHPStan
                run: ./vendor/bin/phpstan analyse src tests --level 5 --debug

            -   name: Run Rector
                run: ./vendor/bin/rector process src tests --dry-run --debug

            -   name: Run PHP CS Fixer
                run: ./vendor/bin/php-cs-fixer fix --dry-run --diff --sequential

            -   name: Lint YAML files
                run: ./vendor/bin/yaml-lint .github/ -vvv --parse-tags

            -   name: Validate PHPMD ruleset
                run: php -r '$dom = new DOMDocument(); $dom->load(".phpmd.xml.dist"); echo "OK\n";'

            -   name: Upload coverage to Codecov
                uses: codecov/codecov-action@v5
                with:
                    files: clover.xml
                    token: ${{ secrets.CODECOV_TOKEN }}
